In [40]:
import numpy as np
import torch

# torch 모듈 정리

## <목차>
[torch.randperm](#randperm)\
[torch.index_select](#index_select)

## torch.randperm <a class="anchor" id="randperm"></a>

```python
torch.randperm(n, *, generator=None, out=None, dtype=torch.int64, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) → Tensor
```

Returns a random permutation of integers from 0 to n - 1 .

- Parameters
n ( int ) – 상한 (배타적)

- 키워드 인수
    - generator ( torch.Generator , 선택 사항) – 샘플링을위한 의사 난수 생성기
    - out ( Tensor , optional ) – 출력 텐서.
    - dtype ( torch.dtype , 선택 사항) – 반환 된 텐서의 원하는 데이터 유형입니다. 기본값 : torch.int64 .
    - layout ( torch.layout , 선택 사항) – 반환 된 Tensor의 원하는 레이아웃입니다. 기본값 : torch.strided .
    - device ( torch.device , optional) – the desired device of returned tensor. Default: if None , uses the current device for the default tensor type (see torch.set_default_tensor_type() ). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.
    - requires_grad ( bool , optional ) – autograd가 반환 된 텐서에 작업을 기록해야하는 경우. 기본값 : False .
    - pin_memory ( bool , optional ) – 설정되면 반환 된 텐서가 고정 된 메모리에 할당됩니다. CPU 텐서에서만 작동합니다. 기본값 : False.

## torch.index_select <a class="anchor" id="index_select"></a>

```python
torch.index_select(input, dim, index, *, out=None) → Tensor
```

Returns a new tensor which indexes the input tensor along dimension dim using the entries in index which is a LongTensor.

The returned tensor has the same number of dimensions as the original tensor (input). The dimth dimension has the same size as the length of index; other dimensions have the same size as in the original tensor.

- Note
    - 반환 된 텐서는 원래 텐서와 동일한 저장소를 사용 하지 않습니다 . 
    - out 의 모양이 예상과 다른 경우 자동으로 올바른 모양으로 변경하여 필요한 경우 기본 저장소를 다시 할당합니다.

- Parameters
    - input ( Tensor ) – 입력 텐서.
    - dim (int) – the dimension in which we index
    - index ( IntTensor 또는 LongTensor ) – 인덱싱 할 인덱스를 포함하는 1 차원 텐서
    - out ( Tensor , optional ) – 출력 텐서.

### 예시
- randperm과 index_select를 섞어 쓰자
- 데이터를 섞고 싶다. X와 y레이블 데이터를 함께 같은 인덱스로 섞어줘야지 참사를 막을 수 있다. 이럴경우 쓰면 좋다.

In [37]:
# 임의 데이터 생성
# x = (10, 2)텐서
x = torch.randint(0, 100, (10, 2))
print(x)

tensor([[35, 95],
        [72, 11],
        [ 4, 88],
        [51, 32],
        [15, 41],
        [39, 74],
        [63, 46],
        [31, 42],
        [13,  0],
        [36, 24]])


In [38]:
n = 10
# 0 ~ 9 까지의 랜덤 순열을 만든다.
indices = torch.randperm(n)
print(indices)

tensor([2, 6, 9, 7, 5, 1, 8, 3, 0, 4])


In [41]:
# 정의한 indices 순서대로 데이터를 섞어 준다
x1 = torch.index_select(x, dim=0, index=indices)
print(x1)

tensor([[ 4, 88],
        [63, 46],
        [36, 24],
        [31, 42],
        [39, 74],
        [72, 11],
        [13,  0],
        [51, 32],
        [35, 95],
        [15, 41]])
